meta_product_name: "PopPin"
meta_title: "PopPin - Select the perfect location for your new Restaurant"
meta_description: "PopPin is the perfect tool to assist you in chosing the perfect location for your new restaurant, based on best data available out there. Try it now!"
meta_image: "Poppin_fb_cover_img.png"
